theme: minima
title: Sunday Summary
author: Madalyn Bartman
# description: I summarize a topic I've learned about every Sunday. Inspired by [this](https://josvisser.substack.com/p/career-advice-learn-how-to-write?r=b67wp&utm_campaign=post&utm_medium=web&triedRedirect=true) blog post by Jos Viser

email: madalynbartman@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Even little thinks matter
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://madalynbartman.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  madalynbartman

plugins:
  - jekyll-feed
  - jekyll-timeago