theme: minima
title: Sunday Summary
author: Madalyn Bartman
description: I summarize a topic I've learned about every Sunday. Inspired by this blog post by Jos Viser: https://josvisser.substack.com/p/career-advice-learn-how-to-write?r=b67wp&utm_campaign=post&utm_medium=web&triedRedirect=true